### Feature Selection by Gradient Boosting Regressor for each neighborhood

In [1]:
# Importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import cross_val_score
from project import handling_missing_values, LabelEncoder
%matplotlib inline

In [2]:
# Reading the data
df = pd.read_csv('train.csv', index_col=0)
df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [3]:
Neighborhood = df['Neighborhood'].unique()

In [4]:
Neighborhood

array(['CollgCr', 'Veenker', 'Crawfor', 'NoRidge', 'Mitchel', 'Somerst',
       'NWAmes', 'OldTown', 'BrkSide', 'Sawyer', 'NridgHt', 'NAmes',
       'SawyerW', 'IDOTRR', 'MeadowV', 'Edwards', 'Timber', 'Gilbert',
       'StoneBr', 'ClearCr', 'NPkVill', 'Blmngtn', 'BrDale', 'SWISU',
       'Blueste'], dtype=object)

In [5]:
for i in Neighborhood:
    vars()[i] = df.loc[df['Neighborhood'] == i]

In [6]:
Veenker

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
54,20,RL,68.0,50271,Pave,NaN,IR1,Low,AllPub,Inside,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,385000
161,20,RL,NaN,11120,Pave,NaN,IR1,Lvl,AllPub,CulDSac,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,162500
327,120,RL,32.0,10846,Pave,NaN,IR1,Lvl,AllPub,CulDSac,...,0,NaN,NaN,NaN,0,5,2008,Con,Normal,324000
401,120,RL,38.0,14963,Pave,NaN,IR2,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,245500
673,20,RL,NaN,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,165000
765,120,RL,30.0,9549,Pave,NaN,IR1,Lvl,AllPub,CulDSac,...,0,NaN,NaN,NaN,0,4,2006,WD,Normal,270000
850,80,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,187000
1156,20,RL,90.0,10768,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,7,2007,WD,Normal,218000
1165,80,RL,NaN,16157,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,6,2007,WD,Normal,194000
1254,60,RL,NaN,17542,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,7,2007,WD,Normal,294000

In [7]:
NPkVill

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
127,120,RL,NaN,4928,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2007,WD,Normal,128000
196,160,RL,24.0,2280,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,7,2009,WD,Normal,148500
505,160,RL,24.0,2308,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2009,WD,Normal,147000
551,120,RL,53.0,4043,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,10,2008,COD,Abnorml,140000
676,160,RL,24.0,2289,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2009,WD,Normal,148500
963,160,RL,24.0,2308,Pave,NaN,Reg,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,7,2007,WD,Normal,155000
1161,160,RL,24.0,2280,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,7,2010,WD,Normal,146000
1422,120,RL,53.0,4043,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,7,2010,WD,Normal,127500
1432,120,RL,NaN,4928,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,10,2009,WD,Normal,143750

In [8]:
var_names = [CollgCr, Veenker, Crawfor, NoRidge, Mitchel, Somerst,NWAmes, OldTown, BrkSide, Sawyer, NridgHt, NAmes,
     SawyerW, IDOTRR, MeadowV, Edwards, Timber, Gilbert,StoneBr, ClearCr, NPkVill, Blmngtn, BrDale, SWISU,Blueste]
var_names[0].head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
14,20,RL,91.0,10652,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,New,Partial,279500
23,20,RL,75.0,9742,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,230000
33,20,RL,85.0,11049,Pave,NaN,Reg,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,1,2008,WD,Normal,179900

In [ ]:
#don't run it does not give what I want
for indx, val in enumerate(Neighborhood):
    var_names[indx].drop(labels = 'Neighborhood', axis=1, inplace=True)
    handling_missing_values(var_names[indx])
    vars()[val] = LabelEncoder(var_names[indx])

In [ ]:
#print(Veenker)

In [9]:
for neighborhood in var_names:
    neighborhood.drop(labels = 'Neighborhood', axis=1, inplace=True)
    handling_missing_values(neighborhood)
    neighborhood = LabelEncoder(neighborhood)

C:\Users\admin1\Anaconda3\lib\site-packages\pandas\core\frame.py:4117: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
C:\Users\admin1\Anaconda3\lib\site-packages\pandas\core\generic.py:5208: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value
C:\Users\admin1\Anaconda3\lib\site-packages\pandas\core\generic.py:6287: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)
C:\Users\admin1\Downloads\Final Project\MachineLearning_FinalProject-master\project.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)

In [10]:
Veenker

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
2,20,3,80.0,9600,2,0,4,Lvl,AllPub,FR2,...,0,0,0,NoMisc,0,5,2007,WD,6,181500
54,20,3,68.0,50271,2,0,3,Low,AllPub,Inside,...,0,0,0,NoMisc,0,11,2006,WD,6,385000
161,20,3,31.0,11120,2,0,3,Lvl,AllPub,CulDSac,...,0,0,0,NoMisc,0,6,2008,WD,6,162500
327,120,3,32.0,10846,2,0,3,Lvl,AllPub,CulDSac,...,0,0,0,NoMisc,0,5,2008,Con,6,324000
401,120,3,38.0,14963,2,0,2,Lvl,AllPub,Inside,...,0,0,0,NoMisc,0,12,2008,WD,6,245500
673,20,3,53.0,11250,2,0,3,Lvl,AllPub,Inside,...,0,0,0,NoMisc,0,6,2006,WD,6,165000
765,120,3,30.0,9549,2,0,3,Lvl,AllPub,CulDSac,...,0,0,0,NoMisc,0,4,2006,WD,6,270000
850,80,3,80.0,9600,2,0,4,Lvl,AllPub,FR2,...,0,0,0,NoMisc,0,8,2007,WD,6,187000
1156,20,3,90.0,10768,2,0,3,Lvl,AllPub,Corner,...,0,0,0,NoMisc,0,7,2007,WD,6,218000
1165,80,3,80.0,16157,2,0,3,Lvl,AllPub,FR2,...,0,0,0,NoMisc,0,6,2007,WD,6,194000
1254,60,3,53.0,17542,2,0,3,Lvl,AllPub,Inside,...,0,0,3,NoMisc,0,7,2007,WD,6,294000

In [11]:
var_names[1]

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
2,20,3,80.0,9600,2,0,4,Lvl,AllPub,FR2,...,0,0,0,NoMisc,0,5,2007,WD,6,181500
54,20,3,68.0,50271,2,0,3,Low,AllPub,Inside,...,0,0,0,NoMisc,0,11,2006,WD,6,385000
161,20,3,31.0,11120,2,0,3,Lvl,AllPub,CulDSac,...,0,0,0,NoMisc,0,6,2008,WD,6,162500
327,120,3,32.0,10846,2,0,3,Lvl,AllPub,CulDSac,...,0,0,0,NoMisc,0,5,2008,Con,6,324000
401,120,3,38.0,14963,2,0,2,Lvl,AllPub,Inside,...,0,0,0,NoMisc,0,12,2008,WD,6,245500
673,20,3,53.0,11250,2,0,3,Lvl,AllPub,Inside,...,0,0,0,NoMisc,0,6,2006,WD,6,165000
765,120,3,30.0,9549,2,0,3,Lvl,AllPub,CulDSac,...,0,0,0,NoMisc,0,4,2006,WD,6,270000
850,80,3,80.0,9600,2,0,4,Lvl,AllPub,FR2,...,0,0,0,NoMisc,0,8,2007,WD,6,187000
1156,20,3,90.0,10768,2,0,3,Lvl,AllPub,Corner,...,0,0,0,NoMisc,0,7,2007,WD,6,218000
1165,80,3,80.0,16157,2,0,3,Lvl,AllPub,FR2,...,0,0,0,NoMisc,0,6,2007,WD,6,194000
1254,60,3,53.0,17542,2,0,3,Lvl,AllPub,Inside,...,0,0,3,NoMisc,0,7,2007,WD,6,294000

In [12]:
Dummy_names = ['CollgCr_D', 'Veenker_D', 'Crawfor_D', 'NoRidge_D', 'Mitchel_D', 'Somerst_D',
       'NWAmes_D', 'OldTown_D', 'BrkSide_D', 'Sawyer_D', 'NridgHt_D', 'NAmes_D',
       'SawyerW_D', 'IDOTRR_D', 'MeadowV_D', 'Edwards_D', 'Timber_D', 'Gilbert_D',
       'StoneBr_D', 'ClearCr_D', 'NPkVill_D', 'Blmngtn_D', 'BrDale_D', 'SWISU_D',
       'Blueste_D']

for indx, val in enumerate(Dummy_names):
    vars()[val] = pd.get_dummies(var_names[indx], drop_first= True)

In [14]:
Veenker_D

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandSlope,OverallQual,OverallCond,...,Exterior1st_Plywood,Exterior1st_Wd Sdng,Exterior1st_WdShing,Exterior2nd_MetalSd,Exterior2nd_Plywood,Exterior2nd_Wd Sdng,Exterior2nd_Wd Shng,MasVnrType_None,Foundation_PConc,SaleType_WD
Id,,,,,,,,,,,,,,,,,,,,,
2,20,3,80.0,9600,2,0,4,1,6,8,...,0,0,0,1,0,0,0,1,0,1
54,20,3,68.0,50271,2,0,3,1,9,5,...,0,0,1,0,0,0,1,1,0,1
161,20,3,31.0,11120,2,0,3,1,6,6,...,1,0,0,0,1,0,0,1,1,1
327,120,3,32.0,10846,2,0,3,1,8,5,...,0,0,0,0,0,0,0,1,1,0
401,120,3,38.0,14963,2,0,2,1,8,5,...,0,0,0,0,0,0,0,1,1,1
673,20,3,53.0,11250,2,0,3,1,6,6,...,1,0,0,0,1,0,0,1,0,1
765,120,3,30.0,9549,2,0,3,1,8,5,...,0,0,0,0,0,0,0,1,1,1
850,80,3,80.0,9600,2,0,4,1,6,7,...,1,0,0,0,1,0,0,0,0,1
1156,20,3,90.0,10768,2,0,3,1,5,8,...,1,0,0,0,1,0,0,1,0,1
1165,80,3,80.0,16157,2,0,3,1,5,7,...,1,0,0,0,1,0,0,1,1,1
1254,60,3,53.0,17542,2,0,3,1,7,7,...,0,1,0,0,0,1,0,1,0,1

In [26]:
Dummy_var = [CollgCr_D, Veenker_D, Crawfor_D, NoRidge_D, Mitchel_D, Somerst_D,NWAmes_D, OldTown_D, BrkSide_D, Sawyer_D, NridgHt_D, NAmes_D,
     SawyerW_D, IDOTRR_D, MeadowV_D, Edwards_D, Timber_D, Gilbert_D,StoneBr_D, ClearCr_D, NPkVill_D, Blmngtn_D, BrDale_D, SWISU_D,Blueste_D]
Dummy_var[1]

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandSlope,OverallQual,OverallCond,...,Exterior1st_Plywood,Exterior1st_Wd Sdng,Exterior1st_WdShing,Exterior2nd_MetalSd,Exterior2nd_Plywood,Exterior2nd_Wd Sdng,Exterior2nd_Wd Shng,MasVnrType_None,Foundation_PConc,SaleType_WD
Id,,,,,,,,,,,,,,,,,,,,,
2,20,3,80.0,9600,2,0,4,1,6,8,...,0,0,0,1,0,0,0,1,0,1
54,20,3,68.0,50271,2,0,3,1,9,5,...,0,0,1,0,0,0,1,1,0,1
161,20,3,31.0,11120,2,0,3,1,6,6,...,1,0,0,0,1,0,0,1,1,1
327,120,3,32.0,10846,2,0,3,1,8,5,...,0,0,0,0,0,0,0,1,1,0
401,120,3,38.0,14963,2,0,2,1,8,5,...,0,0,0,0,0,0,0,1,1,1
673,20,3,53.0,11250,2,0,3,1,6,6,...,1,0,0,0,1,0,0,1,0,1
765,120,3,30.0,9549,2,0,3,1,8,5,...,0,0,0,0,0,0,0,1,1,1
850,80,3,80.0,9600,2,0,4,1,6,7,...,1,0,0,0,1,0,0,0,0,1
1156,20,3,90.0,10768,2,0,3,1,5,8,...,1,0,0,0,1,0,0,1,0,1
1165,80,3,80.0,16157,2,0,3,1,5,7,...,1,0,0,0,1,0,0,1,1,1
1254,60,3,53.0,17542,2,0,3,1,7,7,...,0,1,0,0,0,1,0,1,0,1

In [27]:
top_cols = []
for df in Dummy_var:
    y = np.log(df['SalePrice'])
    x = df.drop(labels = 'SalePrice', axis=1).astype("float64")
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)
    GBR = GradientBoostingRegressor(learning_rate= 0.1, n_estimators=1500, max_depth=2)
    GBR.fit(x_train, y_train)
    important_cols = x.columns[GBR.feature_importances_ > 0.0]
    values = GBR.feature_importances_[GBR.feature_importances_ > 0.0]
    top_cols.append(important_cols[np.where(values==max(values))[0][0]])

ValueError: max() arg is an empty sequence

In [28]:
top_cols

['GrLivArea',
 'BedroomAbvGr',
 'OverallQual',
 'OverallQual',
 'GarageArea',
 'MSSubClass',
 'GrLivArea',
 'GrLivArea',
 'HouseStyle_1Story',
 'GarageType',
 'GrLivArea',
 'GrLivArea',
 'GarageArea',
 'CentralAir',
 'LotArea',
 'TotalBsmtSF',
 'TotalBsmtSF',
 'TotalBsmtSF',
 'YearRemodAdd',
 'BsmtQual',
 'YrSold',
 'BsmtFinSF1',
 'HeatingQC',
 '2ndFlrSF']

In [30]:
len(top_cols)

24

In [29]:
Blueste_D

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandSlope,OverallQual,OverallCond,...,PoolArea,PoolQC,Fence,MiscVal,MoSold,YrSold,SaleCondition,SalePrice,BldgType_TwnhsE,SaleType_WD
Id,,,,,,,,,,,,,,,,,,,,,
600,160,4,24.0,1950,2,0,4,1,6,6,...,0,0,4,0,7,2008,6,151000,0,0
957,160,4,24.0,1300,2,0,4,1,6,6,...,0,0,4,0,5,2009,6,124000,1,1

after the error I checked the list and I found the length is 24 so the problem in last dataframe. As you see above, the last neighborhood has only 2 values so this is not enough for fitting the model. I will remove it from the list.

In [31]:
Dummy_var = [CollgCr_D, Veenker_D, Crawfor_D, NoRidge_D, Mitchel_D, Somerst_D,NWAmes_D, OldTown_D, BrkSide_D, Sawyer_D, NridgHt_D, NAmes_D,
     SawyerW_D, IDOTRR_D, MeadowV_D, Edwards_D, Timber_D, Gilbert_D,StoneBr_D, ClearCr_D, NPkVill_D, Blmngtn_D, BrDale_D, SWISU_D]

In [32]:
top_cols = []
for df in Dummy_var:
    y = np.log(df['SalePrice'])
    x = df.drop(labels = 'SalePrice', axis=1).astype("float64")
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)
    GBR = GradientBoostingRegressor(learning_rate= 0.1, n_estimators=1500, max_depth=2)
    GBR.fit(x_train, y_train)
    important_cols = x.columns[GBR.feature_importances_ > 0.0]
    values = GBR.feature_importances_[GBR.feature_importances_ > 0.0]
    top_cols.append(important_cols[np.where(values==max(values))[0][0]])

In [33]:
top_cols

['GrLivArea',
 'Exterior1st_Plywood',
 'OverallQual',
 'OverallQual',
 'GarageArea',
 'MSSubClass',
 'GrLivArea',
 'GrLivArea',
 'HouseStyle_1Story',
 'GarageType',
 'GrLivArea',
 'GrLivArea',
 'GarageArea',
 'CentralAir',
 'GrLivArea',
 'TotalBsmtSF',
 'TotalBsmtSF',
 'TotalBsmtSF',
 'LotArea',
 'BsmtQual',
 'TotalBsmtSF',
 'TotalBsmtSF',
 'HeatingQC',
 '2ndFlrSF']

In [45]:
list(zip(Neighborhood,top_cols))

[('CollgCr', 'GrLivArea'),
 ('Veenker', 'Exterior1st_Plywood'),
 ('Crawfor', 'OverallQual'),
 ('NoRidge', 'OverallQual'),
 ('Mitchel', 'GarageArea'),
 ('Somerst', 'MSSubClass'),
 ('NWAmes', 'GrLivArea'),
 ('OldTown', 'GrLivArea'),
 ('BrkSide', 'HouseStyle_1Story'),
 ('Sawyer', 'GarageType'),
 ('NridgHt', 'GrLivArea'),
 ('NAmes', 'GrLivArea'),
 ('SawyerW', 'GarageArea'),
 ('IDOTRR', 'CentralAir'),
 ('MeadowV', 'GrLivArea'),
 ('Edwards', 'TotalBsmtSF'),
 ('Timber', 'TotalBsmtSF'),
 ('Gilbert', 'TotalBsmtSF'),
 ('StoneBr', 'LotArea'),
 ('ClearCr', 'BsmtQual'),
 ('NPkVill', 'TotalBsmtSF'),
 ('Blmngtn', 'TotalBsmtSF'),
 ('BrDale', 'HeatingQC'),
 ('SWISU', '2ndFlrSF')]