## Detecting outliers using IsolationForest Algorithm

In [1]:
# Importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import IsolationForest 
%matplotlib inline

In [2]:
# Reading the data
df = pd.read_csv('Numerical_train.csv', index_col=0)
df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandSlope,OverallQual,OverallCond,...,MiscFeature_Shed,MiscFeature_TenC,SaleType_CWD,SaleType_Con,SaleType_ConLD,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD
Id,,,,,,,,,,,,,,,,,,,,,
1,60,3,65.0,8450,2,0,4,1,7,5,...,0,0,0,0,0,0,0,0,0,1
2,20,3,80.0,9600,2,0,4,1,6,8,...,0,0,0,0,0,0,0,0,0,1
3,60,3,68.0,11250,2,0,3,1,7,5,...,0,0,0,0,0,0,0,0,0,1
4,70,3,60.0,9550,2,0,3,1,7,5,...,0,0,0,0,0,0,0,0,0,1
5,60,3,84.0,14260,2,0,3,1,8,5,...,0,0,0,0,0,0,0,0,0,1

In [3]:
y = df['SalePrice']
x = df.drop(labels = 'SalePrice', axis=1).astype("float64")
#x.head()

In [4]:
clf = IsolationForest(random_state=42)

In [5]:
#fitting on the whole dataframe
clf.fit(df)

IsolationForest(behaviour='deprecated', bootstrap=False, contamination='auto',
                max_features=1.0, max_samples='auto', n_estimators=100,
                n_jobs=None, random_state=42, verbose=0, warm_start=False)

In [6]:
df['anomaly'] = clf.predict(df)
df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandSlope,OverallQual,OverallCond,...,MiscFeature_TenC,SaleType_CWD,SaleType_Con,SaleType_ConLD,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,anomaly
Id,,,,,,,,,,,,,,,,,,,,,
1,60,3,65.0,8450,2,0,4,1,7,5,...,0,0,0,0,0,0,0,0,1,1
2,20,3,80.0,9600,2,0,4,1,6,8,...,0,0,0,0,0,0,0,0,1,1
3,60,3,68.0,11250,2,0,3,1,7,5,...,0,0,0,0,0,0,0,0,1,1
4,70,3,60.0,9550,2,0,3,1,7,5,...,0,0,0,0,0,0,0,0,1,1
5,60,3,84.0,14260,2,0,3,1,8,5,...,0,0,0,0,0,0,0,0,1,1

In [7]:
anomaly=df.loc[df['anomaly']==-1]
anomaly

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandSlope,OverallQual,OverallCond,...,MiscFeature_TenC,SaleType_CWD,SaleType_Con,SaleType_ConLD,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,anomaly
Id,,,,,,,,,,,,,,,,,,,,,
524,60,3,130.0,40094,2,0,3,1,10,5,...,0,0,0,0,0,0,1,0,0,-1
636,190,5,60.0,10896,2,2,4,1,6,7,...,0,0,0,0,0,0,0,0,1,-1
706,190,4,70.0,5600,2,0,4,1,4,5,...,0,0,0,0,0,0,0,0,1,-1
1267,190,4,60.0,10120,2,0,3,1,7,4,...,0,0,0,0,0,0,0,0,1,-1
1299,60,3,313.0,63887,2,0,1,1,10,5,...,0,0,0,0,0,0,1,0,0,-1

In [8]:
#fitting without the target column
clf.fit(x)

IsolationForest(behaviour='deprecated', bootstrap=False, contamination='auto',
                max_features=1.0, max_samples='auto', n_estimators=100,
                n_jobs=None, random_state=42, verbose=0, warm_start=False)

In [9]:
df['anomaly'] = clf.predict(x)
df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandSlope,OverallQual,OverallCond,...,MiscFeature_TenC,SaleType_CWD,SaleType_Con,SaleType_ConLD,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,anomaly
Id,,,,,,,,,,,,,,,,,,,,,
1,60,3,65.0,8450,2,0,4,1,7,5,...,0,0,0,0,0,0,0,0,1,1
2,20,3,80.0,9600,2,0,4,1,6,8,...,0,0,0,0,0,0,0,0,1,1
3,60,3,68.0,11250,2,0,3,1,7,5,...,0,0,0,0,0,0,0,0,1,1
4,70,3,60.0,9550,2,0,3,1,7,5,...,0,0,0,0,0,0,0,0,1,1
5,60,3,84.0,14260,2,0,3,1,8,5,...,0,0,0,0,0,0,0,0,1,1

In [10]:
anomaly=df.loc[df['anomaly']==-1]
anomaly

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandSlope,OverallQual,OverallCond,...,MiscFeature_TenC,SaleType_CWD,SaleType_Con,SaleType_ConLD,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,anomaly
Id,,,,,,,,,,,,,,,,,,,,,
89,50,2,105.0,8470,2,0,3,1,3,2,...,0,0,0,1,0,0,0,0,0,-1
524,60,3,130.0,40094,2,0,3,1,10,5,...,0,0,0,0,0,0,1,0,0,-1
636,190,5,60.0,10896,2,2,4,1,6,7,...,0,0,0,0,0,0,0,0,1,-1
706,190,4,70.0,5600,2,0,4,1,4,5,...,0,0,0,0,0,0,0,0,1,-1
1299,60,3,313.0,63887,2,0,1,1,10,5,...,0,0,0,0,0,0,1,0,0,-1

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)

In [12]:
clf.fit(x_train)
x_train['anomaly'] = clf.predict(x_train)
x_test['anomaly'] = clf.predict(x_test)

C:\Users\admin1\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\admin1\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [13]:
anomaly_train = x_train.loc[x_train['anomaly']==-1]
anomaly_train

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandSlope,OverallQual,OverallCond,...,MiscFeature_TenC,SaleType_CWD,SaleType_Con,SaleType_ConLD,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,anomaly
Id,,,,,,,,,,,,,,,,,,,,,
89,50.0,2.0,105.0,8470.0,2.0,0.0,3.0,1.0,3.0,2.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,-1
524,60.0,3.0,130.0,40094.0,2.0,0.0,3.0,1.0,10.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-1
706,190.0,4.0,70.0,5600.0,2.0,0.0,4.0,1.0,4.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,-1
1299,60.0,3.0,313.0,63887.0,2.0,0.0,1.0,1.0,10.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-1
636,190.0,5.0,60.0,10896.0,2.0,2.0,4.0,1.0,6.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,-1
955,90.0,3.0,35.0,9400.0,2.0,0.0,3.0,1.0,6.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,-1
770,60.0,3.0,47.0,53504.0,2.0,0.0,2.0,2.0,8.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,-1

In [14]:
anomaly_test = x_test.loc[x_test['anomaly']==-1]
anomaly_test

Empty DataFrame
Columns: [MSSubClass, MSZoning, LotFrontage, LotArea, Street, Alley, LotShape, LandSlope, OverallQual, OverallCond, YearBuilt, YearRemodAdd, MasVnrArea, ExterQual, ExterCond, BsmtQual, BsmtCond, BsmtExposure, BsmtFinType1, BsmtFinSF1, BsmtFinType2, BsmtFinSF2, BsmtUnfSF, TotalBsmtSF, HeatingQC, CentralAir, 1stFlrSF, 2ndFlrSF, LowQualFinSF, GrLivArea, BsmtFullBath, BsmtHalfBath, FullBath, HalfBath, BedroomAbvGr, KitchenAbvGr, KitchenQual, TotRmsAbvGrd, Functional, Fireplaces, FireplaceQu, GarageType, GarageYrBlt, GarageFinish, GarageCars, GarageArea, GarageQual, GarageCond, PavedDrive, WoodDeckSF, OpenPorchSF, EnclosedPorch, 3SsnPorch, ScreenPorch, PoolArea, PoolQC, Fence, MiscVal, MoSold, YrSold, SaleCondition, LandContour_HLS, LandContour_Low, LandContour_Lvl, Utilities_NoSeWa, LotConfig_CulDSac, LotConfig_FR2, LotConfig_FR3, LotConfig_Inside, Neighborhood_Blueste, Neighborhood_BrDale, Neighborhood_BrkSide, Neighborhood_ClearCr, Neighborhood_CollgCr, Neighborhood_Crawfor, Neighborhood_Edwards, Neighborhood_Gilbert, Neighborhood_IDOTRR, Neighborhood_MeadowV, Neighborhood_Mitchel, Neighborhood_NAmes, Neighborhood_NPkVill, Neighborhood_NWAmes, Neighborhood_NoRidge, Neighborhood_NridgHt, Neighborhood_OldTown, Neighborhood_SWISU, Neighborhood_Sawyer, Neighborhood_SawyerW, Neighborhood_Somerst, Neighborhood_StoneBr, Neighborhood_Timber, Neighborhood_Veenker, Condition1_Feedr, Condition1_Norm, Condition1_PosA, Condition1_PosN, Condition1_RRAe, Condition1_RRAn, Condition1_RRNe, ...]
Index: []

[0 rows x 190 columns]